clc;
close all;
clear all;

fm=10;
phi= pi/4;
fc=10*fm;
t=0:0.0001:1;
sm= 2.*cos(2*pi*fm*t + phi) + cos(3*pi*fm*t);
subplot(3,1,1);
plot(t,sm);
xlabel('T');
ylabel('Amplitude');
title('Message Signal');
grid on;
mf = 10;
sc= 2.*cos(2*pi*fc*t) + cos(3*pi*fc*t);
subplot(3,1,2);
plot(t,sc);
xlabel('Time');
ylabel('Amplitude');
title('Carrier Signal');
grid on;
sf= cos(2*pi*fc*t + (mf.*(2.*sin(2*pi*fm*t + phi)+sin(3*pi*fm*t))))+ cos(3*pi*fc*t + (mf.*(2.*sin(2*pi*fm*t + phi)+sin(3*pi*fm*t))));
subplot(3,1,3);
plot(t,sf);
xlabel('Time');
ylabel('Amplitude');
title('FM Signal');
grid on;
